version: '3.4'

services:
  wesolemotylki:
    image: buttons
    container_name: buttons
    ports:
      - "127.0.0.1:8006:80"
      - "587"
    build:
      context: .
      dockerfile: Buttons.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - internal-net
networks:
  internal-net:
    external: true
